### ISSUE TITLE
build fails on Linux due to v4l2

### ISSUE THREAD

**Issue by joobei** [thp/psmoveapi#77]
Build of some programs fails due to v4l2. I'm on latest ubuntu and I have all the necessary libraries. I followed the build instructions to the letter, just to be sure.

Linking C executable distance_calibration
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_open'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_get_control'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_close'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_set_control'
collect2: error: ld returned 1 exit status
make[2]: *** [distance_calibration] Error 1
make[1]: *** [CMakeFiles/distance_calibration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking C executable test_capture_performance
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_open'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_get_control'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_close'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_set_control'
collect2: error: ld returned 1 exit status
make[2]: *** [test_capture_performance] Error 1
make[1]: *** [CMakeFiles/test_capture_performance.dir/all] Error 2
Linking C executable test_end2end_latency
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_open'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_get_control'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_close'
libpsmoveapi_tracker.so.3.0.0: error: undefined reference to 'v4l2_set_control'
collect2: error: ld returned 1 exit status
make[2]: *** [test_end2end_latency] Error 1
make[1]: *** [CMakeFiles/test_end2end_latency.dir/all] Error 2
Linking CXX shared module _psmove.so
[ 93%] Built target _psmove
make: *** [all] Error 2

I'm on Ubuntu 13.04 Linux 3.8.0-27-generic #40-Ubuntu SMP Tue Jul 9 00:17:05 UTC 2013 x86_64

It only worked when I went into the CMakeLists.txt file and manually added v4l2 to those 4 apps in target_link_libraries

**Comment by tommy-hartmann** [comment]
Sorry for digging up an old thread.

I have the same Problem on Linux Mint 17 (which is based on ubuntu trusty 14.04)
> Distributor ID:	LinuxMint
> Description:	Linux Mint 17.3 Rosa
> Release:	17.3
> Codename:	rosa

output:

> [  8%] Built target psmoveapi
> [ 10%] Built target battery_check
> [ 21%] Built target psmoveapi_tracker
> Linking C executable distance_calibration
> libpsmoveapi_tracker.so...: Nicht definierter Verweis auf `v4l2_get_control'
> libpsmoveapi_tracker.so...: Nicht definierter Verweis auf `v4l2_set_control'
> libpsmoveapi_tracker.so...: Nicht definierter Verweis auf `v4l2_close'
> libpsmoveapi_tracker.so...: Nicht definierter Verweis auf `v4l2_open'
> collect2: error: ld returned 1 exit status
> make[2]: *** [distance_calibration] Fehler 1
> make[1]: *** [CMakeFiles/distance_calibration.dir/all] Fehler 2
> make: *** [all] Fehler 2

I installed libopencv-dev and  libv4l-dev.
How could i solve this problem?
How can i add the v4l2 to my cmake file?

thanks in advance!

**Comment by nitsch** [comment]
I will have a look. From what sources (and description) are you trying to
build?

**Comment by tommy-hartmann** [comment]
I built it from https://github.com/thp/psmoveapi.git with the despription/manual from doc/README.ubuntu

**Comment by nitsch** [comment]
I installed the default Linux Mint 17.3 x64 inside a virtual machine for testing. I cannot reproduce your problem. I did, however, switch to version 3.0.2 of CMake for the build since the default 2.8.12.2 in Linux Mint gave me weird errors I did not want to go investigate further:

> CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
> Missing variable is:
> CMAKE_LANGUAGES_COMPILER_ENV_VAR
> CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
> Missing variable is:
> CMAKE_LANGUAGES_COMPILER
> ...

(also see https://github.com/nexusformat/definitions/issues/401)

But actually libv4l2 should be explicitly set as lib to link against. Not even sure why it works without that. Try adding the following after line 85 in [src/tracker/CMakeLists.txt](https://github.com/thp/psmoveapi/blob/ecdb2bfc8d7795e209e192b01bf5a5efd5c351e0/src/tracker/CMakeLists.txt#L82-L85):
```
list(APPEND PSMOVEAPI_TRACKER_REQUIRED_LIBS v4l2)
```

**Comment by nitsch** [comment]
@tommy-hartmann Any news on this? Does the suggested solution work for you?

**Comment by thp** [comment]
If you build it using the new instructions and/or the updated build script, it should work with Ubuntu 14.04.

**Comment by akatrevorjay** [comment]
I'm seeing the same problems with the new instructions and updated build script. The patch above to add to library to link against fixes it. 16.04 arm64.

**Comment by mhw-Parker** [comment]
`MVideoCapture.cpp:(.text+0x1338): undefined reference to `v4l2_set_control'`
I have the smae problem.
please tell me how to solve this 
thanks!

**Comment by thp** [comment]
@mhw-Parker Please create a new issue. Please also mention there which OS version you are using, and what steps you use to install dependencies and build.
